version: '3.8'

services:
  app:
    image: my-ctf-challenge  # Replace with your desired image name
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    user: ctf:ctf
    volumes:
      - .:/app